-- This is an example migration file that would be generated by Drizzle
-- You don't need to create this manually - it's generated when you run `bun run db:generate`

CREATE TABLE IF NOT EXISTS "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL UNIQUE,
	"name" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "vessels" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"vessel_id" varchar(50) NOT NULL UNIQUE,
	"in_service" boolean DEFAULT false,
	"at_dock" boolean DEFAULT false,
	"latitude" decimal(10,6),
	"longitude" decimal(10,6),
	"heading" decimal(5,1),
	"speed" decimal(5,1),
	"last_updated" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "vessel_positions" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" integer NOT NULL,
	"latitude" decimal(10,6) NOT NULL,
	"longitude" decimal(10,6) NOT NULL,
	"heading" decimal(5,1),
	"speed" decimal(5,1),
	"timestamp" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "vessel_positions_vessel_id_vessels_id_fk" FOREIGN KEY ("vessel_id") REFERENCES "vessels"("id") ON DELETE no action ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "trips" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" integer NOT NULL,
	"departure_port" varchar(100),
	"arrival_port" varchar(100),
	"departure_time" timestamp,
	"arrival_time" timestamp,
	"status" varchar(20) DEFAULT 'scheduled',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "trips_vessel_id_vessels_id_fk" FOREIGN KEY ("vessel_id") REFERENCES "vessels"("id") ON DELETE no action ON UPDATE no action
); 