export default {
  ANA: ["FRI", "LOP", "ORC", "SHA"],
  BBI: ["SEA"],
  BRE: ["SEA"],
  CLI: ["MUK"],
  COU: ["POT"],
  EDM: ["KIN"],
  FAU: ["SOW", "VAS"],
  FRI: ["ANA", "LOP", "ORC", "SHA"],
  KIN: ["EDM"],
  LOP: ["ANA", "FRI", "ORC", "SHA"],
  MUK: ["CLI"],
  ORC: ["ANA", "FRI", "LOP", "SHA"],
  POD: ["TAH"],
  POT: ["COU"],
  SEA: ["BBI", "BRE"],
  SHA: ["ANA", "FRI", "LOP", "ORC"],
  SOW: ["FAU", "VAS"],
  TAH: ["POD"],
  VAS: ["FAU", "SOW"],
};
